### PR TITLE
Few little cosmetic changes and lint error resolved

### PR DESCRIPTION
**Pull request by ghost**
Please comment if you have any questions.

### CODE REVIEW

**Comment by Inversion-NL** [comment]
Great, let me know what you think of it.

**Comment by fabianblom** [comment]
Alright, great that you wanna help making this project better, I will check it out later today or tomorrow. I'm at work now so I dont have much time at the moment.

**Comment by Inversion-NL** [comment]
I understand, no problem.

Currently I'm working on adding a 'first-time-startup-wizard' to help users in connecting to their Toon.
https://vimeo.com/264217265

I've added a dependency in preferences:
https://vimeo.com/264217776

I'v changed the top layout (temp and next program) to have the same size as the buttons below. When on phones with a display size larger than 4" the top layout would be on the left while the rest would stay in the middle.
device-2018-04-11-104724

**Comment by fabianblom** [comment]
Alright looks really good. Great work! I've added you as a collaborator by the way. 👍

**Comment by Inversion-NL** [comment]
Accepted!
Now I just need a working Toon to connect to.
Mine died recently :-(

**Pull request merged**
